echo Building highly backwards Windows compatible (even XP) executable...
dotnet publish -c Release -r win-x86 --self-contained true  -p:PublishAot=true -p:PublishSingleFile=true -p:TrimMode=partial -v detailed
